### ISSUE TITLE
Simple Plugin should reference AbstractPlugin 

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/SimpleRTSPlugin#10]
https://github.com/HydrologicEngineeringCenter/SimpleRTSPlugin/blob/a08c7d284a4900a64cbd4c7409d67d83efc3a86a/src/simplertsplugin/SimpleRTSPluginMain.java#L38

@Tich1212  This class should be only referencing AbstractPlugin if all you want is a tool in a menu item or a tool bar. AbstractSelfContainedPlugin is designed to support plugins in the program order that have no native model with which to interface.

**Comment by Tich1212** [comment]
Good catch!

**Comment by Tich1212** [comment]
@HenryGeorgist I've fixed the class I am extending and implemented the methods in it. See https://github.com/HydrologicEngineeringCenter/SimpleRTSPlugin/commit/bd0d8c9c55b3c9cca28fc2b237f876004c7c255e
