### ISSUE TITLE
Use SimpleRTSPlugin instead of RTSPlugin

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/SimpleRTSPlugin#11]
https://github.com/HydrologicEngineeringCenter/SimpleRTSPlugin/blob/bd0d8c9c55b3c9cca28fc2b237f876004c7c255e/src/simplertsplugin/SimpleRTSPluginMain.java#L41

I believe the unnecessary abstract methods you are getting are coming from the RTSPlugin interface. Change your implements statement to SimpleRTSPlugin and many of those methods will go away.

**Comment by Tich1212** [comment]
Sure did! Changed the interface and removed the unnecessary methods

**Comment by HenryGeorgist** [comment]
please move this from ToDo to Done in the project Kanban
