### ISSUE TITLE
Start a general plugin design document

### ISSUE THREAD

**Issue by Tich1212** [HydrologicEngineeringCenter/SimpleRTSPlugin#4]
What is the plugin intended to do?
Where is it intended to be used?
How will the user setup the plugin?
How will computes be accomplished?
How will results be displayed?
What CAVI components will it rely on?

**Comment by HenryGeorgist** [comment]
Are you creating an example project or are you creating a real project? if it is just an example, I would not recommend a full design document. In general, big design up front is not a good idea. Set a reasonable short term goal, achieve it, and adjust.

**Comment by Tich1212** [comment]
You are right. This should be two projects. The one we are currently working on is setting up a CAVI plugin example that we can use for future plugins. The next step is to use it to build the impact response plugin, which is a separate project, which is what this issue is referring to.

**Comment by HenryGeorgist** [comment]
then i recommend closing this issue and creating a new issue in the repo for the impact response plugin.
